name: NuGet

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v1
            - name: Setup NodeJS
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
                  check-latest: true
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: '5.0.100-rc.1.20452.10'
              env:
                  DOTNET_NOLOGO: true
                  DOTNET_CLI_TELEMETRY_OPTOUT: true

            - name: Build with dotnet
              run: |
                  cd backend
                  dotnet pack --configuration Release
                  mkdir artifacts
                  find . -name '*.nupkg' -exec cp {} ./artifacts \;
                  dotnet nuget add source https://nuget.pkg.github.com/BhanuKorthiwada/index.json -n github -u BhanuKorthiwada -p ${{ secrets.GH_TOKEN }} --store-password-in-clear-text
                  dotnet nuget push ./artifacts/*.nupkg --source "github"

            - uses: actions/upload-artifact@v2
              with:
                  name: nuget-packages
                  path: ./artifacts
