name: .NET Core CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Setup NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: 5.*
        env:
          DOTNET_NOLOGO: true
          DOTNET_CLI_TELEMETRY_OPTOUT: true

      - name: Build with dotnet
        run: dotnet build --configuration Release
