name: Build

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v1
            - name: Setup NodeJS
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
                  check-latest: true
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: '5.0.100-rc.2.20479.15'
              env:
                  DOTNET_NOLOGO: true
                  DOTNET_CLI_TELEMETRY_OPTOUT: true

            - name: Build with dotnet
              run: |
                  cd backend
                  dotnet build --configuration Release
